Views
Pavel-devel/TestGuru--TN pull request #10
Opened 2023-04-04 17:26 UTC by Pavel-devel

2023-04-05 03:17 UTC, VidgarVii requested changes

2023-04-05 03:17 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    def show; end
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2023-04-05 03:17 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +</footer>
No new lina at end of file

2023-04-05 03:18 UTC, VidgarVii requested changes

2023-04-05 03:18 UTC, VidgarVii commented on app/views/tests/index.html.erb
>      <% @tests.each do |test| %>
для рендера коллекций обычно используют render collection
http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy

```ruby
  render @questions
```

- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своей папке
- Позволит удобней кешировать куски страницы

в скринкасте про лэйауты и паршелы рассказывается про рекомендуемый вариант рендеринга коллекций (примерно после 20:30)

2023-04-05 11:03 UTC, Pavel-devel commented on app/views/shared/_footer.html.erb
> +</footer>
+

2023-04-05 11:23 UTC, Pavel-devel commented on app/views/tests/index.html.erb
>      <% @tests.each do |test| %>
+

2023-04-06 04:59 UTC, VidgarVii requested changes

2023-04-06 04:59 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[new create index]
из колбека так же надо удалить индекс

2023-04-06 04:59 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_tests, only: %i[index]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2023-04-06 04:59 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_tests, only: %i[index]
м/у before_action и метдом надо оставлять пустую строку

2023-04-06 04:59 UTC, VidgarVii commented on app/views/questions/edit.html.erb
> +<%= link_to "Back", test_path(@question.test) %>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-04-06 04:59 UTC, VidgarVii commented on app/views/tests/_question.html.erb
> +<% @test.questions.each do |question| %>
https://github.com/Pavel-devel/TestGuru--TN/pull/10#discussion_r1157979291

2023-04-06 04:59 UTC, VidgarVii commented on app/views/tests/_question.html.erb
> +<% @test.questions.each do |question| %>
так же этот файл находится не в своей папке

2023-04-06 04:59 UTC, VidgarVii commented on app/views/tests/_test.html.erb
> +  <td>_____<%= test.questions.count %>_____||</td>
подучи тему css) Я думаю как раз тебе надо оствоить отступы текса в блоках

2023-04-06 04:59 UTC, VidgarVii commented on config/routes.rb
>      resources :questions, shallow: true
https://github.com/Pavel-devel/TestGuru--TN/pull/10#discussion_r1157978457

2023-04-06 07:42 UTC, Pavel-devel commented on app/views/questions/edit.html.erb
> +<%= link_to "Back", test_path(@question.test) %>
+

2023-04-06 07:43 UTC, Pavel-devel commented on app/controllers/tests_controller.rb
> +  before_action :find_tests, only: %i[index]
+

2023-04-06 07:50 UTC, Pavel-devel commented on app/views/tests/_question.html.erb
> +<% @test.questions.each do |question| %>
+

2023-04-06 07:51 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[new create index]
+

2023-04-06 14:47 UTC, Pavel-devel commented on config/routes.rb
>      resources :questions, shallow: true
+

2023-04-06 14:48 UTC, Pavel-devel commented on app/views/tests/_test.html.erb
> +  <td>_____<%= test.questions.count %>_____||</td>
+

2023-04-07 16:51 UTC, merged