Lesson 5
Pavel-devel/TestGuru--TN pull request #5
Opened 2022-12-05 20:28 UTC by Pavel-devel

2022-12-06 03:47 UTC, VidgarVii requested changes

2022-12-06 03:47 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :creator, class_name: 'Author', foreign_key: :creator_id
не работает

2022-12-06 03:47 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :tests_users, dependent: :destroy
вот [пост](https://makandracards.com/makandra/32175-don-t-forget-automatically-remove-join-records-on-has_many-through-associations) в котором на примерах показано как правильно использовать опцию `:dependent` для ассоциации `has_many through`

2022-12-06 03:47 UTC, VidgarVii commented on app/models/user.rb
>    def list_test_by_level(level)
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

2022-12-06 03:47 UTC, VidgarVii commented on app/models/user.rb
нет ассоциации для тестов автора

2023-02-10 18:02 UTC, BubuntuClu requested changes

2023-02-10 18:02 UTC, BubuntuClu commented on .dbeaver/.data-sources.json.bak
> +{
все файлы каких-то локальных настроек твоего окружения не должны попадать в репозиторий. каждый разрабортчик настраиват окружение под себя, твои настройки ему будут не нужны.
добавь это все в гитигнор

2023-02-10 18:02 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, through: :tests_users, dependent: :destroy
смотри, ту добавил сюда `dependent: :destroy`. то есть заложил логику такую - удалил тест, удалил всех пользователей, которые его проходили. а эт тебе зачем?

чтобы такого не происходило, разработчики рельсы предусмотрели это и сделали ограничение на ассоцации с `through`. на них не распротраняется опция `dependent`.
но не всегда за тебя будут думать разработчики инструментов, тебе надо самому понимать что ты пишешь и как это будет работать

2023-02-10 18:02 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, through: :tests_users, dependent: :destroy
тут тоже самое что и в тестах

2023-02-10 18:02 UTC, BubuntuClu commented on config/locales/en.yml
> +  time_left: Time left
слууушай, в этом файле есть такие переводы, о которых ты еще не можешь знать на этом этапе курса.

не смотри на решение других ребят. думай сам, иначе никого смысла от обучения не будет. ты просто накопируешь код, но у тебя не будет понимания как это пишется/как это работает. и потом как ты будешь делать рабочие задачи, если ты не выработаешь навык решения задач по описанию?

2023-02-10 18:02 UTC, BubuntuClu commented on config/locales/en.yml
> +  time_left: Time left
убери все лишнее из переводов

2023-02-12 15:50 UTC, VidgarVii requested changes

2023-02-12 15:50 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions
dependent: :destroy

2023-02-12 15:50 UTC, VidgarVii commented on app/models/user.rb
> +  belongs_to :author, class_name: 'Test'
Юзер и есть автор. Он не может принадлежать не автору ни тесту. Юзер может создать несколько тестов и соответственно быть им автор

2023-02-12 15:50 UTC, VidgarVii commented on config/database.yml
> +  password: 123
username и password у каждого разработчика могут быть разные. не принято такие вещи указывать в репозитории. Такие данные подключают через ENV

2023-02-12 15:50 UTC, VidgarVii commented on config/locales/en.yml
> +  hello: "Hello world"
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-02-12 16:47 UTC, Pavel-devel commented on app/models/test.rb
> +  has_many :questions
+

2023-02-12 16:55 UTC, Pavel-devel commented on config/locales/en.yml
> +  hello: "Hello world"
+

2023-02-13 07:22 UTC, Pavel-devel commented on config/database.yml
> +  password: 123
+

2023-02-13 09:24 UTC, Pavel-devel commented on app/models/user.rb
> +  belongs_to :author, class_name: 'Test'
+

2023-02-14 06:43 UTC, merged