controllers
Pavel-devel/TestGuru--TN pull request #9
Opened 2023-03-24 08:32 UTC by Pavel-devel

2023-03-24 14:08 UTC, VidgarVii requested changes

2023-03-24 14:08 UTC, VidgarVii commented on .gitignore
> +/config/database.yml
если скрываешь database.yml, то стоит создавть файл шаблон database.yml.example

2023-03-24 14:08 UTC, VidgarVii commented on Gemfile
> +  gem 'byebug'
строчкой ниже есть дебагер. 
Кстати самый популярный дебагер является pry

2023-03-24 14:08 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
не указано для какого теста будет создан вопрос

2023-03-24 14:08 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
в этот экшен передаётся еще параметр ид теста. Стоит его использоваться чтобы показать вопросы конкретного теста. Об этом сказано в ТЗ. Не стоит показывать ВСЕ вопросы.

2023-03-24 14:08 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/:test_id/questions" method="post">
параметр action не верный. Что такое :test_id?

2023-03-24 14:08 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +    <input type="text" name="question[test_id]" id="question-test_id">
т.е. через форму можно указать тест для которого создаётся вопрос? Очень странный кейс, когда тест уже задаётся параметром запроса. Смотри ссылку в браузере этой страницы. Форма должна создавать вопрос для **текущего** теста

2023-03-24 14:08 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +
не используется входящий параметр для поиска теста

2023-03-24 14:08 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
параметр test_id не должен передаваться внутри ресурса question.
параметр test_id и так приходит через путь запроса

2023-03-24 15:20 UTC, Pavel-devel commented on .gitignore
> +/config/database.yml
+

2023-03-24 15:48 UTC, Pavel-devel commented on Gemfile
> +  gem 'byebug'
+

2023-03-28 21:39 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +  end
+

2023-03-28 21:39 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +  end
+

2023-03-28 21:39 UTC, Pavel-devel commented on app/views/questions/new.html.erb
> +<form action="/tests/:test_id/questions" method="post">
+

2023-03-28 21:40 UTC, Pavel-devel commented on app/views/questions/new.html.erb
> +    <input type="text" name="question[test_id]" id="question-test_id">
+

2023-03-28 21:40 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +
+

2023-03-28 21:40 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
+

2023-03-29 05:02 UTC, VidgarVii commented on result.txt
> +<!DOCTYPE html>
этот файл не относится к проекту

2023-03-29 05:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.new(test_id: @test.id)
не используешь ассоциации. Зачем делать самим то, что уже реализовано за тебя.

`@question = @test.questions.build`

2023-03-29 05:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to '/'
'/' это root_path
В роутах он определён

2023-03-29 05:45 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +    @question = Question.new(test_id: @test.id)
+

2023-03-29 05:45 UTC, Pavel-devel commented on result.txt
> +<!DOCTYPE html>
+

2023-03-29 05:56 UTC, Pavel-devel commented on app/controllers/questions_controller.rb
> +    redirect_to '/'
+

2023-03-29 06:01 UTC, merged